# Cross-compilation configuration for aarch64
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Configuration for musl targets can be added here if needed
# [target.x86_64-unknown-linux-musl]
# linker = "musl-gcc"
