name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  # Test before release
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Check formatting
      run: cargo fmt --all -- --check

  # Build binaries for different platforms
  build:
    name: Build
    needs: test
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: ai-context-gen-linux-x86_64.tar.gz
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: ai-context-gen-linux-musl-x86_64.tar.gz
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: ai-context-gen-linux-aarch64.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    - name: Install cross-compilation tools
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    - name: Install musl tools
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }}
    - name: Package binary
      run: |
        cd target/${{ matrix.target }}/release
        tar czf ../../../${{ matrix.name }} ai-context-gen
        cd -
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}

  # Create GitHub release
  release:
    name: Create Release
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: Extract changelog entry
      id: changelog
      run: |
        # Extract the changelog entry for this version
        VERSION="${{ steps.get_version.outputs.VERSION }}"
        CHANGELOG_ENTRY=$(awk "/^### $VERSION/{flag=1; next} /^### /{flag=0} flag" README.md)
        echo "CHANGELOG_ENTRY<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG_ENTRY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## What's Changed
          
          ${{ steps.changelog.outputs.CHANGELOG_ENTRY }}
          
          ## Installation
          
          ### Download Binary
          Download the appropriate binary for your platform from the assets below.
          
          ### From Source
          ```bash
          git clone https://github.com/brbtavares/ai-context-gen
          cd ai-context-gen
          git checkout ${{ steps.get_version.outputs.VERSION }}
          make install
          ```
          
          ### As Library
          ```toml
          [dependencies]
          ai-context-gen = "${{ steps.get_version.outputs.VERSION }}"
          ```
        draft: false
        prerelease: false
    
    # Upload all binary assets
    - name: Upload Linux x86_64 Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ai-context-gen-linux-x86_64.tar.gz/ai-context-gen-linux-x86_64.tar.gz
        asset_name: ai-context-gen-linux-x86_64.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Linux musl x86_64 Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ai-context-gen-linux-musl-x86_64.tar.gz/ai-context-gen-linux-musl-x86_64.tar.gz
        asset_name: ai-context-gen-linux-musl-x86_64.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Linux aarch64 Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ai-context-gen-linux-aarch64.tar.gz/ai-context-gen-linux-aarch64.tar.gz
        asset_name: ai-context-gen-linux-aarch64.tar.gz
        asset_content_type: application/gzip

  # Publish to crates.io
  publish:
    name: Publish to crates.io
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
